# Generated by Django 5.2.12 on 2026-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='image_path',
        ),
        migrations.AddField(
            model_name='detection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
    ]
