# Generated by Django 5.2.12 on 2026-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_remove_detection_image_path_detection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
