# Generated by Django 5.2.6 on 2026-03-18 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_alter_detection_detected_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='video_path',
        ),
        migrations.AlterField(
            model_name='detection',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
