# Generated by Django 5.2.6 on 2026-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_remove_detection_video_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='model_type',
            field=models.CharField(choices=[('cart', 'Cart Detection'), ('helmet', 'Helmet Detection')], default='cart', max_length=50),
        ),
        migrations.AddField(
            model_name='detection',
            name='violation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
