# Generated by Django 5.2.15 on 2026-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_detection_model_type_detection_violation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='plate_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
