# Generated by Django 5.2.15 on 2026-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0006_detection_plate_confidence_detection_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
